### ISSUE TITLE
Support exec -it

### ISSUE THREAD

**Issue by jplitza** [fedeztk/kubectl-cautious#1]
When I use `kubectl cautious exec -it`, regardless of whether it is configured in the `cautious.yaml`, I cannot see the output until the executed program/shell exits - which is kind of useless.

It would be great if the buffering between the two `kubectl` invocations could be disabled so that each character is printed while `exec`ing.

**Comment by fedeztk** [comment]
Thanks for opening the issue. I completely forgot to test interactive shells.
The new v0.0.5 release comes with the fix merged from PR #2.

Please, feel free to re-open if not satisfied with the solution.
